name: Clojure tests

# Controls when the action will run.
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run in $GITHUB_WORKSPACE
        run: cd $GITHUB_WORKSPACE

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.693

      - name: Install Emacs
        run: sudo apt-get install -y emacs-nox

      # TODO: Use something better suited for this than Emacs.
      - name: Tangle source files
        run: |
          echo "(dolist (file argv) (message file) (find-file file) (org-babel-tangle))" > compile.el
          emacs --script compile.el deps.org

          cd src
          echo "(dolist (file argv) (message file) (find-file file) (org-babel-tangle))" > compile.el
          emacs --script compile.el *.org
          cd -

      - name: Run Clojure tests
        run: clojure -X:test
